[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "if G.FILE_HANDLER.run then"
position = 'at'
match_indent = true
payload = "if G.FILE_HANDLER.run and (not Balatrogether or not Balatrogether.server or not Balatrogether.server.enabled) then"