[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "if args.key == '0' then args.key = 'o' end"
position = 'at'
match_indent = true
payload = ""